### ISSUE TITLE
Problem when run in Burp on Linux

### ISSUE THREAD

**Issue by davehardy20** [SecurityInnovation/AuthMatrix#1]
Hi,
I tried your extension last night on a windows host and all was fine, however my main pen-testing system is Linux based (Arch Linux, Jython version is 2.7, never had issue with this with any other extensions that require it, Java is version 8) and I added the extension this morning without issue, until I came to create the users and roles in the extension.
The extension took the names for the new users and roles but displayed nothing, so I checked the log in the extender tab, the output is below;

Traceback (most recent call last):
  File "/usr/share/burpsuite/bapps/30d8ee9f40c041b0bfec67441aad158e/AuthMatrix.py", line 327, in getInputUserClick
    self._db.getOrCreateUser(newUser)
  File "/usr/share/burpsuite/bapps/30d8ee9f40c041b0bfec67441aad158e/AuthMatrix.py", line 568, in getOrCreateUser
    self.arrayOfUsers.append(UserEntry(userIndex,
AttributeError: 'java.util.ArrayList' object has no attribute 'append'
Traceback (most recent call last):
  File "/usr/share/burpsuite/bapps/30d8ee9f40c041b0bfec67441aad158e/AuthMatrix.py", line 333, in getInputRoleClick
    self._db.getOrCreateRole(newRole)
  File "/usr/share/burpsuite/bapps/30d8ee9f40c041b0bfec67441aad158e/AuthMatrix.py", line 590, in getOrCreateRole
    self.arrayOfRoles.append(RoleEntry(roleIndex,
AttributeError: 'java.util.ArrayList' object has no attribute 'append'
Traceback (most recent call last):
  File "/usr/share/burpsuite/bapps/30d8ee9f40c041b0bfec67441aad158e/AuthMatrix.py", line 327, in getInputUserClick
    self._db.getOrCreateUser(newUser)
  File "/usr/share/burpsuite/bapps/30d8ee9f40c041b0bfec67441aad158e/AuthMatrix.py", line 568, in getOrCreateUser
    self.arrayOfUsers.append(UserEntry(userIndex,
AttributeError: 'java.util.ArrayList' object has no attribute 'append'
Traceback (most recent call last):
  File "/usr/share/burpsuite/bapps/30d8ee9f40c041b0bfec67441aad158e/AuthMatrix.py", line 333, in getInputRoleClick
    self._db.getOrCreateRole(newRole)
  File "/usr/share/burpsuite/bapps/30d8ee9f40c041b0bfec67441aad158e/AuthMatrix.py", line 590, in getOrCreateRole
    self.arrayOfRoles.append(RoleEntry(roleIndex,
AttributeError: 'java.util.ArrayList' object has no attribute 'append'

If you require any further details please let me know and I'll be happy to help out

Thanks

Dave

**Comment by davehardy20** [comment]
Hi,

I may have worked this out
I checked the downloaded version of Jython27 from the website against the installed version of Jython27 and some of the folders that are included in the downloaded version (bin, extlibs), are missing from the Jython27 folder in the package version.
Looks like this might be an ArchLinux package issue.
Will test further and let you know.

Dave

**Comment by mickayz** [comment]
Sounds good.  I suspect you are correct in that its an issuing with your Jython install.  Let me know if that fixes it.

-Mick

**Comment by mickayz** [comment]
Any update to this?

**Comment by davehardy20** [comment]
I haven't been able to test it properly just yet, I may have chance this
week.

**Comment by mickayz** [comment]
So it looks like this was a mistake in the code that just happened to work for certain versions of java/jython (including mine).  

I pushed an update, version 0.5.1, that should have fixed this.  If you have a chance could you try it out and close this issue if it no longer produces the error?

Thanks for reporting this.

**Comment by serializingme** [comment]
Hi @mickayz,

I had this same exact issue and corrected it in the same way you did it, yes I didn't look at the reported issues in GitHub before hand :) Thankfully I didn't went to the trouble of creating a pull request ahahah :P Anyway, I can confirm that the fix works.

By the way, did you notice that in the BApp the version available is 5.0 instead of 5.1?

Cheers,
Duarte

PS: Great extension by the way, will be testing/using it further this week.

**Comment by coffeetocode** [comment]
Not just Linux. Confirm same (well, equivalent) error on Windows:

- Window 7
- Burp latest (1.6.39)
- Jython 2.7.1b

Confirmed that 0.5.1 update (via commit 18cd2b2111b9c751b33cb37f08aaa9a3a6bf85d9) fixes it. 

Thanks for creating/releasing this. Really badly needed tool, I think it'll do a lot of good.Excited to be trying it out.

**Comment by mickayz** [comment]
Thank you all for the support! v0.5.1 has been submitted to the BApp store and should be updated there soon.
