### ISSUE TITLE
Support for Authorization headers

### ISSUE THREAD

**Issue by iambrosie** [SecurityInnovation/AuthMatrix#11]
When a web application is using OAuth 2.0 authorization flows to access OAuth protected resources, a request looks something along the lines of

```
GET /resource HTTP/1.1
Host: server.example.com
Authorization: Bearer mF_9.B5f-4.1JqM
```

Is it possible to use AuthMatrix in this scenario? (i.e. when web applications employ the Authorization HTTP header for providing authentication information)

Thanks.

**Comment by mickayz** [comment]
By setting the Session Token field of the user to the string "Authorization: Bearer mF_9.B5f-4.1JqM", AuthMatrix should be able to tell that this value is meant to be used as an HTTP header (by identifying the colon in the string).

**Comment by iambrosie** [comment]
Thanks.
Will try as soon as I get the chance.

**Comment by psychoprogrammer** [comment]
Hi @mickayz 

MVC applications contain the RequestVerificationToken header as shown below.

GET /resource HTTP/1.1
Host: server.example.com
RequestVerificationToken: <token>

Anyway to inject this along with Cookie header?

Thanks.

**Comment by mickayz** [comment]
Currently users can set either a header or a set of cookies as the session token, but not both.  In v.0.6 I plan on supporting 3 columns to replace the existing session token and csrf token fields: cookies, http header, and http parameter (CSRF).

Would the inclusion of these 3 fields solve your use case?

**Comment by mickayz** [comment]
support for header column added in v0.6
