### ISSUE TITLE
AuthMatrix Freezing Burp

### ISSUE THREAD

**Issue by heathj** [SecurityInnovation/AuthMatrix#13]
Not really sure what is going on, but every time I run my requests, this extension will freeze Burp completely. I try to right-click on the user accounts and nothing happens. I have to kill the process and restart Burp. Does anyone else have this problem? If I find out more information about this, I'll let you know, but not obvious logs show up.

**Comment by mickayz** [comment]
Not sure if this is the issue, but in v0.6 the request timeouts are handled a lot better if you're host is non responsive.  Should be complete soon, or feel free to try out the version here and see if that fixes your issues:

https://github.com/SecurityInnovation/AuthMatrix/tree/ce17925497fd58f9ed7ce8f48b53880d003b408e

**Comment by heathj** [comment]
This version doesn't seem to crash anymore, but when I make requests they are very slow. And after they are all completed, it takes several seconds to select any of them from the list. It might just be a UI update bug, but not sure. I'll post more information today as I have time to look at it.

**Comment by mickayz** [comment]
Does this occur against all targets? If you right click your requests and select change domain, you can set it to something like google to test against.

This commit should be a bit more stable than the one I posted above:

https://github.com/SecurityInnovation/AuthMatrix/tree/af5e9a8d7da9cd5351eef0887f5ae7f33dec1bfc

**Comment by heathj** [comment]
I had some time to review the source this weekend. I have a couple fixes in the works that I plan on making a merge request for. You can close this issue if you like. Thanks for your help!
