### ISSUE TITLE
Add regular expression or match/replace to user credentials

### ISSUE THREAD

**Issue by dfc** [SecurityInnovation/AuthMatrix#14]
It would be AWESOME if AuthMatrix provided a third option for defining what identifies a user. There are countless times I have been on an engagement and wished i could use authmatrix to test a request that required modifying part of the request in addition-to/instead-of changing session cookies. Adding a regexp or simple match/replace would also let me "unwind the manual for-loop" in other parts of testing process. 

If you really wanted to knock it out of the park you could use something like the positions tab from intruder for super flexibility. 

Give my best to everyone.

**Comment by mickayz** [comment]
In v0.6 I introduce the concept of Chains, which allow you to use regex replacement between requests.  

(i.e. send this value from the response of request 1 to the body of request 3)

Would this solve your use case?

If you're interested, the stable alpha of v0.6 is available at the following URL.  Would love to have some feedback :)

https://github.com/SecurityInnovation/AuthMatrix/tree/823dded54d999c4d30a6acdf50a7139249c6fd01

**Comment by mickayz** [comment]
I believe what you were looking for is supported in v0.6 which is now pushed to master.  Let me know if this doesn't support your use case. Closing this for now.
