### ISSUE TITLE
Request header field is missing ':' separator

### ISSUE THREAD

**Issue by jtkinser** [SecurityInnovation/AuthMatrix#18]
When attempting to run any request I always get the following response:

```
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
Request header field is missing ':' separator.<br />
```

**Comment by mickayz** [comment]
It sounds like the target you are testing against does not like it when an HTTP header is missing a colon. My guess is you have an invalid HTTP Header value for one of your users.

The field expects a value such as this:

"AuthHeader: ASDF"

Could you please provide the values you have in the HTTP Header column of the first table?

**Comment by mickayz** [comment]
Closing.  If this is still an issue, please reopen
