### ISSUE TITLE
Allow detecting 'session invalidated'/logged out state, and re-login

### ISSUE THREAD

**Issue by alias1** [SecurityInnovation/AuthMatrix#22]
It would be cool to be able to auto detect an invalidated/logged out session, and relogin.

Something like:
* Define a login request (eg. POST /login user=foo&pass=bar), and define which cookies/headers/etc to extract from that on a settings tab or similar.
* Allow entering account passwords along with the usernames
* Probably a setting to configure if it should auto-login, and maybe a button for each user; 're-login' or similar (in case you don't want to do it automagically)
* Being able to customize what denotes a 'logged out/invalid session' would be useful as well (see #20 RE: multiple regexes)

The current workaround to this is to notice when the session is invalid/logged out, and manually issue the request through repeater/similar to login, then manually copy the appropriate tokens over, for each user that you have defined.

I came across this issue while testing an app that had rather forced short timeout windows (and interacting with the session didn't extend it)

**Comment by mickayz** [comment]
Agreed, this is useful feature but will take some time to get right.  In the meantime, can you set your first request to the login request and use a chain to update the auth tokens?

**Comment by alias1** [comment]
That's a good question.. hadn't though about that. Will have a look into it :)

Get Outlook for iOS




On Tue, Nov 29, 2016 at 7:47 AM +1100, "mickayz" <notifications@github.com> wrote:












Agreed, this is useful feature but will take some time to get right.  In the meantime, can you set your first request to the login request and use a chain to update the auth tokens?

**Comment by mickayz** [comment]
I've just pushed version 0.7 which updated chains to allow for sourcing from static strings.  The README has more information on the changes, but this screenshot should show an example that will work for your use case.

https://github.com/SecurityInnovation/AuthMatrix/raw/master/images/img6.png

Three chains are being used here.  The first two populate the first request with valid usernames and passwords (defined in the user table).  The third chain pulls the session tokens from the responses of that first request and populates them into the Cookies header of all subsequent requests.

Let me know if you have any questions or comments! :)

**Comment by 0xdevalias** [comment]
This looks really useful, thanks!
