### ISSUE TITLE
Export Requests table as CSV

### ISSUE THREAD

**Issue by alias1** [SecurityInnovation/AuthMatrix#24]
The green/red results are nice, but i'm finding myself having to manually copy/write the data across into a spreadsheet to then pass on to clients.

It would be really awesome if we could export this as a CSV file.

**Comment by mickayz** [comment]
Looking into saving results along with the rest of the state as a CSV in the next release.

Thanks for the suggestion!

**Comment by alias1** [comment]
Awesome :)

**Comment by mickayz** [comment]
Added support for saving and loading state as a human readable JSON file in v0_6_3.  This now includes an array for run results.  More info in the CHANGES file.

Please let me know if you experience any issues.
