### ISSUE TITLE
Load/Update User details from CSV

### ISSUE THREAD

**Issue by alias1** [SecurityInnovation/AuthMatrix#25]
In the current app I am testing (12+ user roles, auth tokens and CSRF headers, really short timeouts) it is sort of a pain to have to go and manually update the auth tokens and CSRF headers all the time.

I've written some python to externally handle the logins, and spit out the required data, but it's a process of copy/pasting at the moment.

It would be cool if we could import/update the user/roles field with a CSV file or similar.

That way, I could have my external code spit everything out in the right format, then a single copy/paste to update AuthMatrix.

Possibly if a column is missing in the CSV, it just isn't updated in AuthMatrix (so we only have to generate the fields we want to update)

**Comment by mickayz** [comment]
Looking into switching saving/loading state as a CSV for the next release. Thanks for the suggestion!

**Comment by alias1** [comment]
Cool :)

**Comment by mickayz** [comment]
Added support for saving and loading state as a human readable JSON file in v0_6_3.  Please let me know if you experience any issues.
