### ISSUE TITLE
Highlight the AuthMatrix tab on 'Send to AuthMatrix'

### ISSUE THREAD

**Issue by 0xdevalias** [SecurityInnovation/AuthMatrix#26]
When we 'send to authmatrix', the tab should get highlighted.

**Comment by mickayz** [comment]
Not directly supported by Burp APIs, but possible with the following strategy.  Will attempt in a later version.

https://support.portswigger.net/customer/portal/questions/14330101-highlight-a-tab

**Comment by mickayz** [comment]
More info here:

https://support.portswigger.net/customer/portal/questions/17131407-highlighting-a-tab-in-jtabbedpane-of-an-extension

**Comment by mickayz** [comment]
Added in commit e11027f
