### ISSUE TITLE
Feature Request [Live mode, add-cookie context menu]

### ISSUE THREAD

**Issue by Hamid-K** [SecurityInnovation/AuthMatrix#27]
I have to use the AuthMatrix again and here are a few more feature requests that I thought having them would be useful for everyone:

1- A  right-click context menu to send the cookies/headers from the current request (in proxy/repeater/...) to the config tab of AuthMatrix so that it can be assigned to a defined user. Even more smooth option would be able to generate a sub-menu for Add-cookie, containing list of defined users in  AuthMatrix. 

2- Auto monitoring of URLs passed through the burp proxy, so that when the user is browsing the application, every proxied request is automatically checked against defined rules. While one can do the same by crawling the app and add all site contents to the AuthMatrix, the live mode will reduce the overall load as well as making it easier to link the actions performed in the UI with back-end requests. This becomes an issue with heavily ajax based applications where lots of background requests are processed for a single click/change in the UI. A similar burp extender named 'Authorize' has already implemented this concept but that plugin has some other issues making it less convenient to use.

Thank you! :)

**Comment by mickayz** [comment]
I really like the idea of having a "Send Cookies to User" right click option. Will be exploring the feasibility of that for the next release.  Auto Monitoring may need additional time to come up with an effective strategy for preventing excessive false positives.

Thanks for the suggestions!

**Comment by mickayz** [comment]
Added initial support for "Send Cookies to User" in v0_6_3.  Please let me know if you experience any issues.  

Closing this out.  Will open a new issue for Live Mode.
