### ISSUE TITLE
Option for GET parameters

### ISSUE THREAD

**Issue by freb** [SecurityInnovation/AuthMatrix#30]
My first time using this, but so far it's amazing. In the application I'm testing, they are passing the CSRF token via GET parameter in a few locations. While this is an issue by itself, I still need to test the application logic.

If this is something you would include, I can implement and submit a PR.

**Comment by freb** [comment]
I found a pretty workable solution, thanks to some hints from your video: https://www.youtube.com/watch?v=pMXTmXUsEL8

I am using the `Python Scripter` extension to replace a get parameter placeholder based on a session ID found in the body of the request. In case anyone needs something similar, here is the code:

```python
import sys,re

# example: https://www.ernw.de/download/pythonScriptExample.py

def add_csrf_get_param(request):
    PLACEHOLDER = "CSRF_TOKEN_PLACEHOLDER"

    # map session ids to csrf tokens
    csrf_map = {
        "sessid1": "csrftoken1",
        "sessid2": "csrftoken2",
        "sessid3": "csrftoken3",
        "sessid4": "csrftoken4",
    }

    # map session ids to user names
    user_map = {
        "sessid1": "user1",
        "sessid2": "user2",
        "sessid3": "user3",
        "sessid4": "user4",
    }

    if not request.startswith("GET"):
        print "> not a get request"
        return request
    if not PLACEHOLDER in request:
        print "> placeholder not in request"
        return request
    for sid, csrf in csrf_map.items():
        if sid in request:
            request = request.replace(PLACEHOLDER, "CSRFToken="+csrf)
            print "> added csrf token as get parameter for %s" % user_map[sid]
            return request
    print "> session id not found"
    return request

try:
    if messageIsRequest and toolFlag == callbacks.TOOL_EXTENDER:
        print "> Processing request"
        request = helpers.bytesToString(messageInfo.getRequest())
        request = add_csrf_get_param(request)
        messageInfo.setRequest(request)
        print "> done processing request"

except:
    print sys.exc_info()
```

There is something weird with global variables in Python Scripter due to its use of exec that I didn't want to take the time to investigate (just in case you were wondering why my maps are inside the function).

**Comment by mickayz** [comment]
Just a heads up, you should be able to define Chains for this use case as you can replace items anywhere in the request.  As of v0.7 you can replace these with either extracted values from a previous request or static user values.
