### ISSUE TITLE
Feature: Separate color for when request does not succeed on checked role

### ISSUE THREAD

**Issue by mickayz** [SecurityInnovation/AuthMatrix#5]
If a user configures the table and sees a checked role box in the message table that is red after run, it usually implies that the success regex is incorrect or the session tokens have expired.  Consider coloring that box a different color than red to indicate this error to the user.

**Comment by forkrul** [comment]
Would also be useful to indicate false positives with a different colour.

**Comment by mickayz** [comment]
Added in v0.5.3
