### ISSUE TITLE
Allow enabling/disabling of users, request, and chains

### ISSUE THREAD

**Issue by ArneSwinnen** [SecurityInnovation/AuthMatrix#51]
It would be extremely useful to allow temporary enabling/disabling of users. For example, when I want to quickly check whether a DELETE request can be performed by other users than the owner, I would like to exclude the owner for this request run. 

I would see this as a simple checkbox in front of each user row in the user table, which will be taken into account in the request table (no request sent for unchecked but existing users).

**Comment by mickayz** [comment]
Added right click options to chains, requests, and users in commit 9700263
