### ISSUE TITLE
Bug: Saving empty states

### ISSUE THREAD

**Issue by mickayz** [SecurityInnovation/AuthMatrix#53]
In certain rare cases, an empty value is written during a state save. 

No reliable repro steps as of yet.

A warning will be added in 7.1

**Comment by Mason-Fan** [comment]
@mickayz , i encountered this issue. i have about 100+ request and three roles. every time when i save the result after running, it will create a 0 byte file. does the result size exceed some limitation?

**Comment by mickayz** [comment]
I believe this has to do with an uncaught exception when generating the output for the state file. My guess is the specific cause is when one of the requests times out, the response is empty and it causes an exception when its dereferenced somewhere. Given you have 100 requests, it seems fairly likely that one of them will have timed out in the last run.

I'm pushing a beta fix to the following branch.  If you have a chance, give it a try and let me know if that fixes the problem.

https://github.com/securityinnovation/authmatrix/tree/7.1beta

**Comment by mickayz** [comment]
Went ahead and merged with master, as I'm pretty sure this is fixed.  Please re-open this issue if you're still seeing the bug.

Thanks for reporting! Sorry if it caused you to lose some work.

**Comment by Mason-Fan** [comment]
tested with new version. it solves the issue like a magic. Thanks!
