### ISSUE TITLE
SyntaxError: ("no viable alternative at input 'for'", ('**********\\Roaming\\BurpSuite\\bapps\\30d8ee9f40c041b0bfec67441aad158e\\AuthMatrix.py', 1319, 58, ''))

### ISSUE THREAD

**Issue by 0xNone** [SecurityInnovation/AuthMatrix#56]
SyntaxError: ("no viable alternative at input 'for'", ('**********\\Roaming\\BurpSuite\\bapps\\30d8ee9f40c041b0bfec67441aad158e\\AuthMatrix.py', 1319, 58, ''))

**Comment by mickayz** [comment]
Can you provide what version of Jython you are using?

 Any specific repro steps that cause this?

**Comment by 0xNone** [comment]
1. I' m use `jython-standalone-2.5.3`
![image](https://user-images.githubusercontent.com/16507416/32131583-63e11544-bbe4-11e7-80db-10c6d9042100.png)
2. I chose `AuthMatrix` installation in `Bapp store`
![image](https://user-images.githubusercontent.com/16507416/32131591-b3e4fdc6-bbe4-11e7-827a-87173f048522.png)
3. When I want to start `AuthMatrix`
![image](https://user-images.githubusercontent.com/16507416/32131598-cd01c82a-bbe4-11e7-872f-eff24492b2ad.png)

I don't know what's wrong with it. Can you help me?

**Comment by mickayz** [comment]
Currently AuthMatrix only supports standalone Jython 2.7.0 or greater.  Version 2.7.0 recognizes some syntax that is not supported in older versions, including python list comprehension which is used throughout AuthMatrix. This requirement is noted in the Readme of AuthMatrix.

If you can, try with the 2.7.0 jar available here.  

http://www.jython.org/downloads.html

If you are still experiencing issues, let me know and we can reopen the issue.

-Mick

**Comment by 0xNone** [comment]
Thank you. I'm so stupid. Why didn't I try more version. Repaired.
