### ISSUE TITLE
Adding session tokens instead of replacing them

### ISSUE THREAD

**Issue by exploresecurity** [SecurityInnovation/AuthMatrix#6]
Hi
Working on an app that has multiple session tokens so in the session token field I've put e.g.
**a=1; b=2**
When I came to run the test AuthMatrix has _added_ those tokens to the original request, not replaced them. So in the Cookie field for a request from the above user I'd have something like:
**a=5; b=6; a=1; b=2**
where a=5 and b=6 came from the _original_ request. Surely AuthMatrix should _replace_ the values of cookies from the original request. If the app is using the first session management values it encounters then the above does not switch users/roles as a=1; b=2 will be ignored.
Is this because AuthMatrix cannot handle multiple session tokens, or some other bug?
Thanks

**Comment by mickayz** [comment]
Thank you for reporting this issue! Its true this should have awareness of multiple session tokens separated by semi colons. Adding it to the list of bugs to be fixed.

**Comment by mickayz** [comment]
This should now be working in version 0.5.2. Let me know if it is not working as expected.

Thanks,
-Mick

**Comment by exploresecurity** [comment]
Hi, just got time for a quick look but it seems to be handling this scenario as expected now.
Thanks for the speedy patch.
Jerome
