### ISSUE TITLE
Option to 'blank' cookies

### ISSUE THREAD

**Issue by 0xdevalias** [SecurityInnovation/AuthMatrix#67]
Currently we can blank cookies by setting the value to an empty string:

```
foo=
```

This is ok in a number of use cases, but sometimes we want to strip all of the cookies (of which there might be many), or maybe we don't want to send the cookie at all (even if it is set to blank).

Currently there doesn't seem to be a good solution for this?

I would have expected that by leaving the cookies blank, that all cookies would be removed, but that will just leave all of the original cookies on the request.

**Comment by mickayz** [comment]
For multiple cookies, you can blank them out by setting that field as follows:

foo=;bar=;xyz=

In order to remove cookies from the request you can either edit the original request body to remove them, or you can add a header set to:

Cookies: 

Do these solutions work for your use case?

**Comment by mickayz** [comment]
I'm hesitant to change the default behavior.  It may be the case that certain cookies must remain in the requests and are not related to auth, in which case we would not want AuthMatrix to clear all of them automatically.

**Comment by 0xdevalias** [comment]
Yeah, definitely agree that we shouldn't default to 'remove all'.

* Blanking manually is doable, but kind of annoying (in a once per app way though.. so probably bearable)
* Editing original request is annoying (in an every request added way), but probably still bearable
* Adding the new header sounds like a nice solution, but when I tried it just now it didn't seem to work (anonymous user still had all the cookies on the request):

User Name: `Anonymous`
Cookies: ``
HTTP Header: `Cookie:`

**Comment by 0xdevalias** [comment]
Actually.. there might be another bug.

I added a new header (`Cookie:`), ran it, all the cookies were there.

Changed the header to `Cookie: a=b`, ran it, no cookies were there
Ran it again, cookies were `a=b`

**Comment by mickayz** [comment]
Ah, I think the bug here is that if you click run and the table field is still editting (with a cursor) the field is not updating. 

Can you confirm that if you finish editting the field (by pressing enter) and then running, the results are expected?

If that is the case, I can create a new issue that clicking the run button should complete the editting for all table fields.

**Comment by 0xdevalias** [comment]
Yup, hitting enter first certainly seems to be working as expected.

**Comment by mickayz** [comment]
Good :)

Since the custom header option fits your use case, I'll consider this issue closed and open a separate one for the unsaved field.

Thanks for using the software and reporting issues :)

**Comment by 0xdevalias** [comment]
Sounds good :)
