### ISSUE TITLE
how to keep cookie alive?

### ISSUE THREAD

**Issue by grayguest** [SecurityInnovation/AuthMatrix#73]
if i have many users, i only have 3 browsers, it means only 3 cookie is valid in meanwhile, but it can not verify all users.

**Comment by mickayz** [comment]
Thanks for posting. Authmatrix should work independently of any web browsers. For strategies for keeping cookies alive, I recommend using chains to automatically refresh cookies at the beginning of each run.

See the following image from the readme for an example of how to authenticate the users using chains:

https://github.com/SecurityInnovation/AuthMatrix/raw/master/images/img6.png

**Comment by grayguest** [comment]
thank you very much.
