### ISSUE TITLE
Fail Regex

### ISSUE THREAD

**Issue by mickayz** [SecurityInnovation/AuthMatrix#9]
There may be the need for a failure regex as well in cases where the desired condition can't be mapped with a success regex alone.

eg:
Fail case: "Not Authorized" in response body
Success case: Returns specific user's name (unique to each user and not regex-able)

**Comment by securitygeneration** [comment]
1+

**Comment by mickayz** [comment]
Just a heads up, this has been implemented and will be undergoing testing.  It should be pushed to master once that is done.

**Comment by mickayz** [comment]
This has been added to v.0.5.4

Please submit any bug reports to the issues section here.

**Comment by mickayz** [comment]
The implementation in v0.5.4 had a bug. It is now fixed in v0.6.1 which is pushed to master.
 
View the README for a proper usage example.
